Production_planing_web/Models/ErrorViewModel.cs
using System;

namespace Production_planing_web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Production_planing_web/Controllers/ApiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Production_planing_web.Controllers
{
    public class ApiController : Controller
    {
        // GET: ApiController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Model()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public void Login()
        {

        }

    }
}

Production_planing_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Production_planing_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @if (IsSectionDefined("Header"))
        {
            @RenderSection("Header")
        }
        else
        {
            <!--Navbar-->
            <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                <!--Brand link-->
                <a class="navbar-brand" asp-area="" asp-controller="Api" asp-action="About">Production planning</a>
                <!--Collapsible button-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--Links-->
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Api" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Api" asp-action="Model">Model configurator</a>
                        </li>
                    </ul>
                </div>
            </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Production_planing_web - <a asp-area="" asp-controller="Api" asp-action="About">About</a>
        </div>
    </footer>

    @*ок какойто скрипт чтобы всё работало*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>